export const AEPSTWO_STATUS_CHECK_SUCCESS = "AEPSTWO_STATUS_CHECK_SUCCESS";
export const AEPSTWO_STATUS_CHECK_FAILURE = "AEPSTWO_STATUS_CHECK_FAILURE";

export const AEPSTWO_ONBOARDING_SUCCESS = "AEPSTWO_ONBOARDING_SUCCESS";
export const AEPSTWO_ONBOARDING_FAILURE = "AEPSTWO_ONBOARDING_FAILURE";

export const AEPSTWO_SEND_OTP_SUCCESS = "AEPSTWO_SEND_OTP_SUCCESS";
export const AEPSTWO_SEND_OTP_FAILURE = "AEPSTWO_SEND_OTP_FAILURE";

export const AEPSTWO_RESEND_OTP_SUCCESS = "AEPSTWO_RESEND_OTP_SUCCESS";
export const AEPSTWO_RESEND_OTP_FAILURE = "AEPSTWO_RESEND_OTP_FAILURE";

export const AEPSTWO_SUBMIT_OTP_SUCCESS = "AEPSTWO_SUBMIT_OTP_SUCCESS";
export const AEPSTWO_SUBMIT_OTP_FAILURE = "AEPSTWO_SUBMIT_OTP_FAILURE";