export const AEPS_TERMS_CONDITION_OTP_SUCCESS = 'AEPS_TERMS_CONDITION_OTP_SUCCESS';
export const AEPS_TERMS_CONDITION_OTP_FAILURE = 'AEPS_TERMS_CONDITION_OTP_FAILURE';

export const AEPS_STATUS_CHECK_SUCCESS = 'AEPS_STATUS_CHECK_SUCCESS';
export const AEPS_STATUS_CHECK_FAILURE = 'AEPS_STATUS_CHECK_FAILURE';

export const AEPS_RESCEND_OTP_SUCCESS = 'AEPS_RESCEND_OTP_SUCCESS';
export const AEPS_RESCEND_OTP_FAILURE = 'AEPS_RESCEND_OTP_FAILURE';

export const AEPS_SUBMIT_OTP_SUCCESS = 'AEPS_SUBMIT_OTP_SUCCESS';
export const AEPS_SUBMIT_OTP_FAILURE = 'AEPS_SUBMIT_OTP_FAILURE';

export const AEPS_ONBOARDING_BIOMETRIC_VERIFICATION_SUCCESS = 'AEPS_ONBOARDING_BIOMETRIC_VERIFICATION_SUCCESS';
export const AEPS_ONBOARDING_BIOMETRIC_VERIFICATION_FAILURE = 'AEPS_ONBOARDING_BIOMETRIC_VERIFICATION_FAILURE';

export const AEPS_ONBOARDING_FA_VERIFICATION_SUCCESS = 'AEPS_ONBOARDING_FA_VERIFICATION_SUCCESS';
export const AEPS_ONBOARDING_FA_VERIFICATION_FAILURE = 'AEPS_ONBOARDING_2FA_VERIFICATION_FAILURE';

export const AEPS_CW_HISTORY_SUCCESS = 'AEPS_CW_HISTORY_SUCCESS';
export const AEPS_CW_HISTORY_FAILURE = 'AEPS_CW_HISTORY_FAILURE';

export const AEPS_BANK_LIST_SUCCESS = 'AEPS_BANK_LIST_SUCCESS';
export const AEPS_BANK_LIST_FAILURE = 'AEPS_BANK_LIST_FAILURE';

export const AEPS_WITHDRAWAL_SUCCESS = 'AEPS_WITHDRAWAL_SUCCESS';
export const AEPS_WITHDRAWAL_FAILURE = 'AEPS_WITHDRAWAL_FAILURE';

export const AEPS_TRANSACTION_DETAILS_SUCCESS = 'AEPS_TRANSACTION_DETAILS_SUCCESS';
export const AEPS_TRANSACTION_DETAILS_FAILURE = 'AEPS_TRANSACTION_DETAILS_FAILURE';

export const AEPS_BANK_OTP_SUCCESS = 'AEPS_BANK_OTP_SUCCESS';
export const AEPS_BANK_OTP_FAILURE = 'AEPS_BANK_OTP_FAILURE';

export const AEPS_BANK_OTP_SUBMIT_SUCCESS = 'AEPS_BANK_OTP_SUBMIT_SUCCESS';
export const AEPS_BANK_OTP_SUBMIT_FAILURE = 'AEPS_BANK_OTP_SUBMIT_FAILURE';

export const AEPS_BANK_KYC_SUCCESS = 'AEPS_BANK_KYC_SUCCESS';
export const AEPS_BANK_KYC_FAILURE = 'AEPS_BANK_KYC_FAILURE';

export const AEPS_CW_HISTORY_COMPANY_SUCCESS = 'AEPS_CW_HISTORY_COMPANY_SUCCESS';
export const AEPS_CW_HISTORY_COMPANY_FAILURE = 'AEPS_CW_HISTORY_COMPANY_FAILURE';

export const AEPS_RESENT_BANK_LIST_SUCCESS = 'AEPS_RESENT_BANK_LIST_SUCCESS';
export const AEPS_RESENT_BANK_LIST_FAILURE = 'AEPS_RESENT_BANK_LIST_FAILURE';

export const AEPS_CW_HISTORY_USER_SUCCESS = 'AEPS_CW_HISTORY_USER_SUCCESS';
export const AEPS_CW_HISTORY_USER_FAILURE = 'AEPS_CW_HISTORY_USER_FAILURE';