export const AEPSTWO_STATUS_CHECK_SUCCESS = "AEPSTWO_STATUS_CHECK_SUCCESS";
export const AEPSTWO_STATUS_CHECK_FAILURE = "AEPSTWO_STATUS_CHECK_FAILURE";

export const AEPSTWO_ONBOARDING_SUCCESS = "AEPSTWO_ONBOARDING_SUCCESS";
export const AEPSTWO_ONBOARDING_FAILURE = "AEPSTWO_ONBOARDING_FAILURE";

export const AEPSTWO_SEND_OTP_SUCCESS = "AEPSTWO_SEND_OTP_SUCCESS";
export const AEPSTWO_SEND_OTP_FAILURE = "AEPSTWO_SEND_OTP_FAILURE";

export const AEPSTWO_RESEND_OTP_SUCCESS = "AEPSTWO_RESEND_OTP_SUCCESS";
export const AEPSTWO_RESEND_OTP_FAILURE = "AEPSTWO_RESEND_OTP_FAILURE";

export const AEPSTWO_SUBMIT_OTP_SUCCESS = "AEPSTWO_SUBMIT_OTP_SUCCESS";
export const AEPSTWO_SUBMIT_OTP_FAILURE = "AEPSTWO_SUBMIT_OTP_FAILURE";

export const AEPSTWO_BIOMETRIC_VERIFICATION_SUCCESS = "AEPSTWO_BIOMETRIC_VERIFICATION_SUCCESS";
export const AEPSTWO_BIOMETRIC_VERIFICATION_FAILURE = "AEPSTWO_BIOMETRIC_VERIFICATION_FAILURE";

export const AEPSTWO_TWO_FA_VERIFICATION_SUCCESS = "AEPSTWO_TWO_FA_VERIFICATION_SUCCESS";
export const AEPSTWO_TWO_FA_VERIFICATION_FAILURE = "AEPSTWO_TWO_FA_VERIFICATION_FAILURE";

export const AEPSTWO_CASH_WITHDRAWL_SUCCESS = "AEPSTWO_CASH_WITHDRAWL_SUCCESS";
export const AEPSTWO_CASH_WITHDRAWL_FAILURE = "AEPSTWO_CASH_WITHDRAWL_FAILURE";

export const AEPSTWO_BALANCE_ENQUIRY_SUCCESS = "AEPSTWO_BALANCE_ENQUIRY_SUCCESS";
export const AEPSTWO_BALANCE_ENQUIRY_FAILURE = "AEPSTWO_BALANCE_ENQUIRY_FAILURE";

export const AEPSTWO_MINI_STATEMENT_SUCCESS = "AEPSTWO_MINI_STATEMENT_SUCCESS";
export const AEPSTWO_MINI_STATEMENT_FAILURE = "AEPSTWO_MINI_STATEMENT_FAILURE";

export const AEPSTWO_BANKLIST_SUCCESS = "AEPSTWO_BANKLIST_SUCCESS";
export const AEPSTWO_BANKLIST_FAILURE = "AEPSTWO_BANKLIST_FAILURE";

export const AEPSTWO_RESENT_BANK_LIST_SUCCESS = "AEPSTWO_RESENT_BANK_LIST_SUCCESS";
export const AEPSTWO_RESENT_BANK_LIST_FAILURE = "AEPSTWO_RESENT_BANK_LIST_FAILURE";

export const AEPSTWO_CW_HISTORY_SUCCESS = "AEPSTWO_CW_HISTORY_SUCCESS";
export const AEPSTWO_CW_HISTORY_FAILURE = "AEPSTWO_CW_HISTORY_FAILURE";

export const AEPSTWO_CW_HISTORY_COMPANY_SUCCESS = "AEPSTWO_CW_HISTORY_COMPANY_SUCCESS";
export const AEPSTWO_CW_HISTORY_COMPANY_FAILURE = "AEPSTWO_CW_HISTORY_COMPANY_FAILURE";