export const AEPS_TERMS_CONDITION_OTP_SUCCESS = 'AEPS_TERMS_CONDITION_OTP_SUCCESS';
export const AEPS_TERMS_CONDITION_OTP_FAILURE = 'AEPS_TERMS_CONDITION_OTP_FAILURE';

export const AEPS_STATUS_CHECK_SUCCESS = 'AEPS_STATUS_CHECK_SUCCESS';
export const AEPS_STATUS_CHECK_FAILURE = 'AEPS_STATUS_CHECK_FAILURE';

export const AEPS_CW_HISTORY_SUCCESS = 'AEPS_CW_HISTORY_SUCCESS';
export const AEPS_CW_HISTORY_FAILURE = 'AEPS_CW_HISTORY_FAILURE';
