export const AEPS_TERMS_CONDITION_OTP_SUCCESS = 'AEPS_TERMS_CONDITION_OTP_SUCCESS';
export const AEPS_TERMS_CONDITION_OTP_FAILURE = 'AEPS_TERMS_CONDITION_OTP_FAILURE';

export const AEPS_STATUS_CHECK_SUCCESS = 'AEPS_STATUS_CHECK_SUCCESS';
export const AEPS_STATUS_CHECK_FAILURE = 'AEPS_STATUS_CHECK_FAILURE';

export const AEPS_RESCEND_OTP_SUCCESS = 'AEPS_RESCEND_OTP_SUCCESS';
export const AEPS_RESCEND_OTP_FAILURE = 'AEPS_RESCEND_OTP_FAILURE';

export const AEPS_SUBMIT_OTP_SUCCESS = 'AEPS_SUBMIT_OTP_SUCCESS';
export const AEPS_SUBMIT_OTP_FAILURE = 'AEPS_SUBMIT_OTP_FAILURE';

export const AEPS_ONBOARDING_BIOMETRIC_VERIFICATION_SUCCESS  = 'AEPS_ONBOARDING_BIOMETRIC_VERIFICATION_SUCCESS';
export const AEPS_ONBOARDING_BIOMETRIC_VERIFICATION_FAILURE = 'AEPS_ONBOARDING_BIOMETRIC_VERIFICATION_FAILURE';

export const AEPS_ONBOARDING_FA_VERIFICATION_SUCCESS = 'AEPS_ONBOARDING_FA_VERIFICATION_SUCCESS';
export const AEPS_ONBOARDING_FA_VERIFICATION_FAILURE = 'AEPS_ONBOARDING_2FA_VERIFICATION_FAILURE';

export const AEPS_CW_HISTORY_SUCCESS = 'AEPS_CW_HISTORY_SUCCESS';
export const AEPS_CW_HISTORY_FAILURE = 'AEPS_CW_HISTORY_FAILURE';
