export const AEPSTHREE_STATUS_CHECK_SUCCESS = "AEPSTHREE_STATUS_CHECK_SUCCESS";
export const AEPSTHREE_STATUS_CHECK_FAILURE = "AEPSTHREE_STATUS_CHECK_FAILURE";

export const AEPSTHREE_ONBOARDING_SUCCESS = "AEPSTHREE_ONBOARDING_SUCCESS";
export const AEPSTHREE_ONBOARDING_FAILURE = "AEPSTHREE_ONBOARDING_FAILURE";

export const AEPSTHREE_SEND_OTP_SUCCESS = "AEPSTHREE_SEND_OTP_SUCCESS";
export const AEPSTHREE_SEND_OTP_FAILURE = "AEPSTHREE_SEND_OTP_FAILURE";

export const AEPSTHREE_RESEND_OTP_SUCCESS = "AEPSTHREE_RESEND_OTP_SUCCESS";
export const AEPSTHREE_RESEND_OTP_FAILURE = "AEPSTHREE_RESEND_OTP_FAILURE";

export const AEPSTHREE_SUBMIT_OTP_SUCCESS = "AEPSTHREE_SUBMIT_OTP_SUCCESS";
export const AEPSTHREE_SUBMIT_OTP_FAILURE = "AEPSTHREE_SUBMIT_OTP_FAILURE";

export const AEPSTHREE_BIOMETRIC_VERIFICATION_SUCCESS = "AEPSTHREE_BIOMETRIC_VERIFICATION_SUCCESS";
export const AEPSTHREE_BIOMETRIC_VERIFICATION_FAILURE = "AEPSTHREE_BIOMETRIC_VERIFICATION_FAILURE";

export const AEPSTHREE_TWO_FA_VERIFICATION_SUCCESS = "AEPSTHREE_TWO_FA_VERIFICATION_SUCCESS";
export const AEPSTHREE_TWO_FA_VERIFICATION_FAILURE = "AEPSTHREE_TWO_FA_VERIFICATION_FAILURE";

export const AEPSTHREE_CASH_WITHDRAWL_SUCCESS = "AEPSTHREE_CASH_WITHDRAWL_SUCCESS";
export const AEPSTHREE_CASH_WITHDRAWL_FAILURE = "AEPSTHREE_CASH_WITHDRAWL_FAILURE";

export const AEPSTHREE_BALANCE_ENQUIRY_SUCCESS = "AEPSTHREE_BALANCE_ENQUIRY_SUCCESS";
export const AEPSTHREE_BALANCE_ENQUIRY_FAILURE = "AEPSTHREE_BALANCE_ENQUIRY_FAILURE";

export const AEPSTHREE_MINI_STATEMENT_SUCCESS = "AEPSTHREE_MINI_STATEMENT_SUCCESS";
export const AEPSTHREE_MINI_STATEMENT_FAILURE = "AEPSTHREE_MINI_STATEMENT_FAILURE";

export const AEPSTHREE_BANKLIST_SUCCESS = "AEPSTHREE_BANKLIST_SUCCESS";
export const AEPSTHREE_BANKLIST_FAILURE = "AEPSTHREE_BANKLIST_FAILURE";

export const AEPSTHREE_RESENT_BANK_LIST_SUCCESS = "AEPSTHREE_RESENT_BANK_LIST_SUCCESS";
export const AEPSTHREE_RESENT_BANK_LIST_FAILURE = "AEPSTHREE_RESENT_BANK_LIST_FAILURE";

export const AEPSTHREE_CW_HISTORY_SUCCESS = "AEPSTHREE_CW_HISTORY_SUCCESS";
export const AEPSTHREE_CW_HISTORY_FAILURE = "AEPSTHREE_CW_HISTORY_FAILURE";

export const AEPSTHREE_CW_HISTORY_COMPANY_SUCCESS = "AEPSTHREE_CW_HISTORY_COMPANY_SUCCESS";
export const AEPSTHREE_CW_HISTORY_COMPANY_FAILURE = "AEPSTHREE_CW_HISTORY_COMPANY_FAILURE";

export const AEPSTHREE_CW_HISTORY_USERS_SUCCESS = "AEPSTHREE_CW_HISTORY_USERS_SUCCESS";
export const AEPSTHREE_CW_HISTORY_USERS_FAILURE = "AEPSTHREE_CW_HISTORY_USERS_FAILURE";

export const AEPSTHREE_CW_HISTORY_TRANSACTION_DETAILS_SUCCESS = "AEPSTHREE_CW_HISTORY_TRANSACTION_DETAILS_SUCCESS";
export const AEPSTHREE_CW_HISTORY_TRANSACTION_DETAILS_FAILURE = "AEPSTHREE_CW_HISTORY_TRANSACTION_DETAILS_FAILURE";

export const AEPSTHREE_CW_HISTORY_EMPLOYEE_SUCCESS = "AEPSTHREE_CW_HISTORY_EMPLOYEE_SUCCESS";
export const AEPSTHREE_CW_HISTORY_EMPLOYEE_FAILURE = "AEPSTHREE_CW_HISTORY_EMPLOYEE_FAILURE";
