export const BBPS_GET_ALL_CATEGORIES_START = 'BBPS_GET_ALL_CATEGORIES_START';
export const BBPS_GET_ALL_CATEGORIES_SUCCESS = 'BBPS_GET_ALL_CATEGORIES_SUCCESS';
export const BBPS_GET_ALL_CATEGORIES_FAILURE = 'BBPS_GET_ALL_CATEGORIES_FAILURE';

export const BBPS_CREATE_CATEGORY_START = 'BBPS_CREATE_CATEGORY_START';
export const BBPS_CREATE_CATEGORY_SUCCESS = 'BBPS_CREATE_CATEGORY_SUCCESS';
export const BBPS_CREATE_CATEGORY_FAILURE = 'BBPS_CREATE_CATEGORY_FAILURE';

export const BBPS_UPDATE_CATEGORY_START = 'BBPS_UPDATE_CATEGORY_START';
export const BBPS_UPDATE_CATEGORY_SUCCESS = 'BBPS_UPDATE_CATEGORY_SUCCESS';
export const BBPS_UPDATE_CATEGORY_FAILURE = 'BBPS_UPDATE_CATEGORY_FAILURE';

export const BBPS_SEARCH_CATEGORIES_START = 'BBPS_SEARCH_CATEGORIES_START';
export const BBPS_SEARCH_CATEGORIES_SUCCESS = 'BBPS_SEARCH_CATEGORIES_SUCCESS';
export const BBPS_SEARCH_CATEGORIES_FAILURE = 'BBPS_SEARCH_CATEGORIES_FAILURE';

export const BBPS_GET_ALL_BILLERS_START = 'BBPS_GET_ALL_BILLERS_START';
export const BBPS_GET_ALL_BILLERS_SUCCESS = 'BBPS_GET_ALL_BILLERS_SUCCESS';
export const BBPS_GET_ALL_BILLERS_FAILURE = 'BBPS_GET_ALL_BILLERS_FAILURE';

export const BBPS_SEARCH_BILLERS_START = 'BBPS_SEARCH_BILLERS_START';
export const BBPS_SEARCH_BILLERS_SUCCESS = 'BBPS_SEARCH_BILLERS_SUCCESS';
export const BBPS_SEARCH_BILLERS_FAILURE = 'BBPS_SEARCH_BILLERS_FAILURE';

export const BBPS_GET_CATEGORIES_FOR_DROPDOWN_START = 'BBPS_GET_CATEGORIES_FOR_DROPDOWN_START';
export const BBPS_GET_CATEGORIES_FOR_DROPDOWN_SUCCESS = 'BBPS_GET_CATEGORIES_FOR_DROPDOWN_SUCCESS';
export const BBPS_GET_CATEGORIES_FOR_DROPDOWN_FAILURE = 'BBPS_GET_CATEGORIES_FOR_DROPDOWN_FAILURE';

export const BBPS_GET_ALL_PAYMENT_INFO_START = 'BBPS_GET_ALL_PAYMENT_INFO_START';
export const BBPS_GET_ALL_PAYMENT_INFO_SUCCESS = 'BBPS_GET_ALL_PAYMENT_INFO_SUCCESS';
export const BBPS_GET_ALL_PAYMENT_INFO_FAILURE = 'BBPS_GET_ALL_PAYMENT_INFO_FAILURE';

export const BBPS_SEARCH_PAYMENT_INFO_START = 'BBPS_SEARCH_PAYMENT_INFO_START';
export const BBPS_SEARCH_PAYMENT_INFO_SUCCESS = 'BBPS_SEARCH_PAYMENT_INFO_SUCCESS';
export const BBPS_SEARCH_PAYMENT_INFO_FAILURE = 'BBPS_SEARCH_PAYMENT_INFO_FAILURE';

export const BBPS_CREATE_PAYMENT_INFO_START = 'BBPS_CREATE_PAYMENT_INFO_START';
export const BBPS_CREATE_PAYMENT_INFO_SUCCESS = 'BBPS_CREATE_PAYMENT_INFO_SUCCESS';
export const BBPS_CREATE_PAYMENT_INFO_FAILURE = 'BBPS_CREATE_PAYMENT_INFO_FAILURE';

export const BBPS_UPDATE_PAYMENT_INFO_START = 'BBPS_UPDATE_PAYMENT_INFO_START';
export const BBPS_UPDATE_PAYMENT_INFO_SUCCESS = 'BBPS_UPDATE_PAYMENT_INFO_SUCCESS';
export const BBPS_UPDATE_PAYMENT_INFO_FAILURE = 'BBPS_UPDATE_PAYMENT_INFO_FAILURE';

export const BBPS_CREATE_BILLER_START = 'BBPS_CREATE_BILLER_START';
export const BBPS_CREATE_BILLER_SUCCESS = 'BBPS_CREATE_BILLER_SUCCESS';
export const BBPS_CREATE_BILLER_FAILURE = 'BBPS_CREATE_BILLER_FAILURE';

export const BBPS_UPDATE_BILLER_START = 'BBPS_UPDATE_BILLER_START';
export const BBPS_UPDATE_BILLER_SUCCESS = 'BBPS_UPDATE_BILLER_SUCCESS';
export const BBPS_UPDATE_BILLER_FAILURE = 'BBPS_UPDATE_BILLER_FAILURE';

// User BBPS Categories
export const BBPS_USER_GET_ALL_CATEGORIES_START = 'BBPS_USER_GET_ALL_CATEGORIES_START';
export const BBPS_USER_GET_ALL_CATEGORIES_SUCCESS = 'BBPS_USER_GET_ALL_CATEGORIES_SUCCESS';
export const BBPS_USER_GET_ALL_CATEGORIES_FAILURE = 'BBPS_USER_GET_ALL_CATEGORIES_FAILURE';
