export const RETAILER_FUND_GET_ALL_BANKS_SUCCESS = 'RETAILER_FUND_GET_ALL_BANKS_SUCCESS';
export const RETAILER_FUND_GET_ALL_BANKS_FAILURE = 'RETAILER_FUND_GET_ALL_BANKS_FAILURE';

export const RETAILER_FUND_LOAD_SUCCESS = 'RETAILER_FUND_LOAD_SUCCESS';
export const RETAILER_FUND_LOAD_FAILURE = 'RETAILER_FUND_LOAD_FAILURE';

export const DISTRIBUTOR_FUND_GET_ALL_BANKS_SUCCESS = 'DISTRIBUTOR_FUND_GET_ALL_BANKS_SUCCESS';
export const DISTRIBUTOR_FUND_GET_ALL_BANKS_FAILURE = 'DISTRIBUTOR_FUND_GET_ALL_BANKS_FAILURE';

export const MASTER_DISTRIBUTOR_FUND_GET_ALL_BANKS_SUCCESS = 'MASTER_DISTRIBUTOR_FUND_GET_ALL_BANKS_SUCCESS';
export const MASTER_DISTRIBUTOR_FUND_GET_ALL_BANKS_FAILURE = 'MASTER_DISTRIBUTOR_FUND_GET_ALL_BANKS_FAILURE';

export const DISTRIBUTOR_FUND_LOAD_SUCCESS = 'DISTRIBUTOR_FUND_LOAD_SUCCESS';
export const DISTRIBUTOR_FUND_LOAD_FAILURE = 'DISTRIBUTOR_FUND_LOAD_FAILURE';

export const MASTER_DISTRIBUTOR_FUND_LOAD_SUCCESS = 'MASTER_DISTRIBUTOR_FUND_LOAD_SUCCESS';
export const MASTER_DISTRIBUTOR_FUND_LOAD_FAILURE = 'MASTER_DISTRIBUTOR_FUND_LOAD_FAILURE';

export const MASTER_DISTRIBUTOR_FUND_REQUEST_SUCCESS = 'MASTER_DISTRIBUTOR_FUND_REQUEST_SUCCESS';
export const MASTER_DISTRIBUTOR_FUND_REQUEST_FAILURE = 'MASTER_DISTRIBUTOR_FUND_REQUEST_FAILURE';

export const DISTRIBUTOR_FUND_REQUEST_SUCCESS = 'DISTRIBUTOR_FUND_REQUEST_SUCCESS';
export const DISTRIBUTOR_FUND_REQUEST_FAILURE = 'DISTRIBUTOR_FUND_REQUEST_FAILURE';

export const MASTER_DISTRIBUTOR_FUND_APPROVE_SUCCESS = 'MASTER_DISTRIBUTOR_FUND_APPROVE_SUCCESS';
export const MASTER_DISTRIBUTOR_FUND_APPROVE_FAILURE = 'MASTER_DISTRIBUTOR_FUND_APPROVE_FAILURE';

export const DISTRIBUTOR_FUND_APPROVE_SUCCESS = 'DISTRIBUTOR_FUND_APPROVE_SUCCESS';
export const DISTRIBUTOR_FUND_APPROVE_FAILURE = 'DISTRIBUTOR_FUND_APPROVE_FAILURE';

export const COMPANY_BANK_LIST_SUCCESS = 'COMPANY_BANK_LIST_SUCCESS';
export const COMPANY_BANK_LIST_FAILURE = 'COMPANY_BANK_LIST_FAILURE';

export const COMPANY_FUND_LOAD_SUCCESS = 'COMPANY_FUND_LOAD_SUCCESS';
export const COMPANY_FUND_LOAD_FAILURE = 'COMPANY_FUND_LOAD_FAILURE';

export const COMPANY_GET_ALL_REQUEST_SUCCESS = 'COMPANY_GET_ALL_REQUEST_SUCCESS';
export const COMPANY_GET_ALL_REQUEST_FAILURE = 'COMPANY_GET_ALL_REQUEST_FAILURE';

export const COMPANY_APPROVE_REQUEST_SUCCESS = 'COMPANY_APPROVE_REQUEST_SUCCESS';
export const COMPANY_APPROVE_REQUEST_FAILURE = 'COMPANY_APPROVE_REQUEST_FAILURE';
 
export const ADMIN_REQUEST_SUCCESS = 'ADMIN_REQUEST_SUCCESS';
export const ADMIN_REQUEST_FAILURE = 'ADMIN_REQUEST_FAILURE';

export const ADMIN_APPROVE_SUCCESS = 'ADMIN_APPROVE_SUCCESS';
export const ADMIN_APPROVE_FAILURE = 'ADMIN_APPROVE_FAILURE';

export const PAN_SERVICE_REQUEST_SUCCESS = 'PAN_SERVICE_REQUEST_SUCCESS';
export const PAN_SERVICE_REQUEST_FAILURE = 'PAN_SERVICE_REQUEST_FAILURE';