export const HELP_CONTACT_SUPPORT_SUCCESS = 'HELP_CONTACT_SUPPORT_SUCCESS';
export const HELP_CONTACT_SUPPORT_FAILURE = 'HELP_CONTACT_SUPPORT_FAILURE';

export const REMOVE_CONTACT_NUMBER_SUCCESS = 'REMOVE_CONTACT_NUMBER_SUCCESS';
export const REMOVE_CONTACT_NUMBER_FAILURE = 'REMOVE_CONTACT_NUMBER_FAILURE';

export const ADD_SUPPORT_PHONE_SUCCESS = 'ADD_SUPPORT_PHONE_SUCCESS';
export const ADD_SUPPORT_PHONE_FAILURE = 'ADD_SUPPORT_PHONE_FAILURE';

export const ADD_SUPPORT_EMAIL_SUCCESS = 'ADD_SUPPORT_EMAIL_SUCCESS';
export const ADD_SUPPORT_EMAIL_FAILURE = 'ADD_SUPPORT_EMAIL_FAILURE';
