export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const VERIFICATION_OTP_SUCCESS = 'VERIFICATION_OTP_SUCCESS';
export const VERIFICATION_OTP_FAILURE = 'VERIFICATION_OTP_FAILURE';

export const TWOFACTOR_AUTH_SUCCESS = 'TWOFACTOR_AUTH_SUCCESS';
export const TWOFACTOR_AUTH_FAILURE = 'TWOFACTOR_AUTH_FAILURE';

export const RESECEND_OTP_SUCCESS = 'RESECEND_OTP_SUCCESS';
export const RESECEND_OTP_FAILURE = 'RESECEND_OTP_FAILURE';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILURE = 'FORGET_PASSWORD_FAILURE';

export const VERIFY_FORGET_PASSWORD_SUCCESS = 'VERIFY_FORGET_PASSWORD_SUCCESS';
export const VERIFY_FORGET_PASSWORD_FAILURE = 'VERIFY_FORGET_PASSWORD_FAILURE';

export const VERIFY_MPIN_SUCCESS = 'VERIFY_MPIN_SUCCESS';
export const VERIFY_MPIN_FAILURE = 'VERIFY_MPIN_FAILURE';

export const SET_MPIN_SUCCESS = 'SET_MPIN_SUCCESS';
export const SET_MPIN_FAILURE = 'SET_MPIN_FAILURE';


export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FORGET_MPIN_SUCCESS = 'FORGET_MPIN_SUCCESS';
export const FORGET_MPIN_FAILURE = 'FORGET_MPIN_FAILURE';

export const VERIFY_MPIN_OTP_SUCCESS = 'VERIFY_MPIN_OTP_SUCCESS';
export const VERIFY_MPIN_OTP_FAILURE = 'VERIFY_MPIN_OTP_FAILURE';