export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const VERIFICATION_OTP_SUCCESS = 'VERIFICATION_OTP_SUCCESS';
export const VERIFICATION_OTP_FAILURE = 'VERIFICATION_OTP_FAILURE';

export const TWOFACTOR_AUTH_SUCCESS = 'TWOFACTOR_AUTH_SUCCESS';
export const TWOFACTOR_AUTH_FAILURE = 'TWOFACTOR_AUTH_FAILURE';

