export const FETCH_ONBOARDING_START = 'FETCH_ONBOARDING_START';
export const FETCH_ONBOARDING_SUCCESS = 'FETCH_ONBOARDING_SUCCESS';
export const FETCH_ONBOARDING_FAILURE = 'FETCH_ONBOARDING_FAILURE';
export const CLEAR_ONBOARDING = 'CLEAR_ONBOARDING';
export const UPDATE_ONBOARDING_STEP = 'UPDATE_ONBOARDING_STEP';


export const MOBILE_OTP_SENT_SUCCESS = "MOBILE_OTP_SENT_SUCCESS";
export const MOBILE_OTP_SENT_FAILURE = 'MOBILE_OTP_SENT_FAILURE';

export const SMS_VERIFY_OTP_SUCCESS = "SMS_VERIFY_OTP_SUCCESS";
export const SMS_VERIFY_OTP_FAILURE = "SMS_VERIFY_OTP_FAILURE";

export const SMS_RESEND_OTP_SUCCESS = "SMS_RESCEND_OTP_SUCCESS";
export const SMS_RESEND_OTP_FAILURE = "SMS_RECEND_OTP_FAILURE";

export const EMAIL_OTP_SENT_SUCCESS = "EMAIL_OPT_SENT_SUCCESS";
export const EMAIL_OTP_SENT_FAILURE = "EMAIL_OPT_SENT_FAILURE";

export const EMAIL_RESCEND_OTP_SUCCESS = "EMAIL_RESCEND_OTP_SUCCESS";
export const EMAIL_RESCEND_OTP_FAILURE = "EMAIL_RESCEND_OTP_FAILURE";

export const EMAIL_VERIFY_OTP_SUCCESS = "EMAIL_VERIFY_OTP_SUCCESS";
export const EMAIL_VERIFY_OTP_FAILURE = "EMAIL_VERIFY_OTP_FAILURE";

export const AADHAAR_CONNECTION_SUCCESS = "AADHAAR_CONNECTION_SUCCESS";
export const AADHAAR_CONNECTION_FAILURE = "AADHAAR_CONNECTION_FAILURE";

export const DOWNLOAD_AADHAAR_SUCCESS = "DOWNLOAD_AADHAAR_SUCCESS";
export const DOWNLOAD_AADHAAR_FAILURE = "DOWNLOAD_AADHAAR_FAILURE";

export const UPLOAD_AADHAAR_SUCCESS = "UPLOAD_AADHAAR_SUCCESS";
export const UPLOAD_AADHAAR_FAILURE = "UPLOAD_AADHAAR_FAILURE";

export const PAN_CONNECTION_SUCCESS = "PAN_CONNECTION_SUCCESS";
export const PAN_CONNECTION_FAILURE = "PAN_CONNECTION_FAILURE";

export const DOWNLOAD_PAN_SUCCESS = "DOWNLOAD_PAN_SUCCESS";
export const DOWNLOAD_PAN_FAILURE = "DOWNLOAD_PAN_FAILURE";

export const UPLOAD_PAN_SUCCESS = "UPLOAD_PAN_SUCCESS";
export const UPLOAD_PAN_FAILURE = "UPLOAD_PAN_FAILURE";

export const POST_BANK_DETAILS_SUCCESS = "POST_BANK_DETAILS_SUCCESS";
export const POST_BANK_DETAILS_FAILURE = "POST_BANK_DETAILS_FAILURE";

export const POST_PROFILE_START = "POST_PROFILE_START";
export const POST_PROFILE_SUCCESS = "POST_PROFILE_SUCCESS";
export const POST_PROFILE_FAILURE = "POST_PROFILE_FAILURE";

export const POST_SHOP_DETAILS_START = "POST_SHOP_DETAILS_START";
export const POST_SHOP_DETAILS_SUCCESS = "POST_SHOP_DETAILS_SUCCESS";
export const POST_SHOP_DETAILS_FAILURE = "POST_SHOP_DETAILS_FAILURE";
