export const OPERATOR_LIST_SUCCESS = "OPERATOR_LIST_SUCCESS";
export const OPERATOR_LIST_FAILURE = "OPERATOR_LIST_FAILURE";

export const OPERATOR_CREATE_SUCCESS = "OPERATOR_CREATE_SUCCESS";
export const OPERATOR_CREATE_FAILURE = "OPERATOR_CREATE_FAILURE";

export const OPERATOR_UPDATE_SUCCESS = "OPERATOR_UPDATE_SUCCESS";
export const OPERATOR_UPDATE_FAILURE = "OPERATOR_UPDATE_FAILURE";

export const ADMIN_UPGRADE_LIST_SUCCESS = 'ADMIN_UPGRADE_LIST_SUCCESS';
export const ADMIN_UPGRADE_LIST_FAILURE = 'ADMIN_UPGRADE_LIST_FAILURE';