export const PAYOUT_BANK_LIST_SUCCESS = "PAYOUT_BANK_LIST_SUCCESS";
export const PAYOUT_BANK_LIST_FAILURE = "PAYOUT_BANK_LIST_FAILURE";

export const PAYOUT_TRANSACTION_SUCCESS = "PAYOUT_TRANSACTION_SUCCESS";
export const PAYOUT_TRANSACTION_FAILURE = "PAYOUT_TRANSACTION_FAILURE";

export const COMPANY_PAYOUT_BANK_LIST_SUCCESS =
  "COMPANY_PAYOUT_BANK_LIST_SUCCESS";
export const COMPANY_PAYOUT_BANK_LIST_FAILURE =
  "COMPANY_PAYOUT_BANK_LIST_FAILURE";

export const COMPANY_PAYOUT_TRANSACTION_SUCCESS =
  "COMPANY_PAYOUT_TRANSACTION_SUCCESS";
export const COMPANY_PAYOUT_TRANSACTION_FAILURE =
  "COMPANY_PAYOUT_TRANSACTION_FAILURE";

export const PAYOUT_HISTORY_SUCCESS = "PAYOUT_HISTORY_SUCCESS";
export const PAYOUT_HISTORY_FAILURE = "PAYOUT_HISTORY_FAILURE";

// ✅ COMPANY PAYOUT HISTORY
export const PAYOUT_HISTORY_COMPANY_SUCCESS = "PAYOUT_HISTORY_COMPANY_SUCCESS";
export const PAYOUT_HISTORY_COMPANY_FAILURE = "PAYOUT_HISTORY_COMPANY_FAILURE";

// ✅ USER PAYOUT HISTORY
export const PAYOUT_HISTORY_USER_SUCCESS = "PAYOUT_HISTORY_USER_SUCCESS";
export const PAYOUT_HISTORY_USER_FAILURE = "PAYOUT_HISTORY_USER_FAILURE";

// ✅ PAYOUT SETTING
export const PAYOUT_SETTING_LIST_SUCCESS = "PAYOUT_SETTING_LIST_SUCCESS";
export const PAYOUT_SETTING_LIST_FAILURE = "PAYOUT_SETTING_LIST_FAILURE";
export const PAYOUT_SETTING_CREATE_SUCCESS = "PAYOUT_SETTING_CREATE_SUCCESS";
export const PAYOUT_SETTING_CREATE_FAILURE = "PAYOUT_SETTING_CREATE_FAILURE";
export const PAYOUT_SETTING_SWITCH_SUCCESS = "PAYOUT_SETTING_SWITCH_SUCCESS";
export const PAYOUT_SETTING_SWITCH_FAILURE = "PAYOUT_SETTING_SWITCH_FAILURE";
