export const PAYOUT_BANK_LIST_SUCCESS = 'PAYOUT_BANK_LIST_SUCCESS'
export const PAYOUT_BANK_LIST_FAILURE = 'PAYOUT_BANK_LIST_FAILURE'

export const PAYOUT_TRANSACTION_SUCCESS = 'PAYOUT_TRANSACTION_SUCCESS'
export const PAYOUT_TRANSACTION_FAILURE = 'PAYOUT_TRANSACTION_FAILURE'

export const COMPANY_PAYOUT_BANK_LIST_SUCCESS = 'COMPANY_PAYOUT_BANK_LIST_SUCCESS'
export const COMPANY_PAYOUT_BANK_LIST_FAILURE = 'COMPANY_PAYOUT_BANK_LIST_FAILURE'

export const COMPANY_PAYOUT_TRANSACTION_SUCCESS = 'COMPANY_PAYOUT_TRANSACTION_SUCCESS'
export const COMPANY_PAYOUT_TRANSACTION_FAILURE = 'COMPANY_PAYOUT_TRANSACTION_FAILURE'