export const FIND_MOBILE_OPERATOR_SUCCESS = 'FIND_MOBILE_OPERATOR_SUCCESS';
export const FIND_MOBILE_OPERATOR_FAILURE = 'FIND_MOBILE_OPERATOR_FAILURE';

export const FIND_MOBILE_RECHARGE_PLAN_SUCCESS = 'FIND_MOBILE_RECHARGE_PLAN_SUCCESS';
export const FIND_MOBILE_RECHARGE_PLAN_FAILURE = 'FIND_MOBILE_RECHARGE_PLAN_FAILURE';

export const FIND_MOBILE_RECHARGE_OFFERS_SUCCESS = 'FIND_MOBILE_RECHARGE_OFFERS_SUCCESS';
export const FIND_MOBILE_RECHARGE_OFFERS_FAILURE = 'FIND_MOBILE_RECHARGE_OFFERS_FAILURE';

export const PAY_RECHARGE_SUCCESS = 'PAY_RECHARGE_SUCCESS';
export const PAY_RECHARGE_FAILURE = 'PAY_RECHARGE_FAILURE';