export const FIND_MOBILE_OPERATOR_SUCCESS = 'FIND_MOBILE_OPERATOR_SUCCESS';
export const FIND_MOBILE_OPERATOR_FAILURE = 'FIND_MOBILE_OPERATOR_FAILURE';

export const FIND_MOBILE_RECHARGE_PLAN_SUCCESS = 'FIND_MOBILE_RECHARGE_PLAN_SUCCESS';
export const FIND_MOBILE_RECHARGE_PLAN_FAILURE = 'FIND_MOBILE_RECHARGE_PLAN_FAILURE';

export const FIND_MOBILE_RECHARGE_OFFERS_SUCCESS = 'FIND_MOBILE_RECHARGE_OFFERS_SUCCESS';
export const FIND_MOBILE_RECHARGE_OFFERS_FAILURE = 'FIND_MOBILE_RECHARGE_OFFERS_FAILURE';

export const PAY_RECHARGE_SUCCESS = 'PAY_RECHARGE_SUCCESS';
export const PAY_RECHARGE_FAILURE = 'PAY_RECHARGE_FAILURE';

export const FIND_DTH_OPERATOR_INFO_SUCCESS = 'FIND_DTH_OPERATOR_INFO_SUCCESS';
export const FIND_DTH_OPERATOR_INFO_FAILURE = 'FIND_DTH_OPERATOR_INFO_FAILURE';

export const DTH_RECHARGE_PLAN_FETCH_SUCCESS = 'DTH_RECHARGE_PLAN_FETCH_SUCCESS';
export const DTH_RECHARGE_PLAN_FETCH_FAILURE = 'DTH_RECHARGE_PLAN_FETCH_FAILURE';

export const DTH_RECHARGE_SUCCESS = 'DTH_RECHARGE_SUCCESS';
export const DTH_RECHARGE_FAILURE = 'DTH_RECHARGE_FAILURE';

export const RECENT_HISTORY_SUCCESS = 'RECENT_HISTORY_SUCCESS';
export const RECENT_HISTORY_FAILURE = 'RECENT_HISTORY_FAILURE';

export const CMS_PROCESS_STATUS_SUCCESS = 'CMS_PROCESS_STATUS_SUCCESS';
export const CMS_PROCESS_STATUS_FAILURE = 'CMS_PROCESS_STATUS_FAILURE';