export const ADMIN_TXN_REPORT_SUCCESS = 'ADMIN_TXN_REPORT_SUCCESS'
export const ADMIN_TXN_REPORT_FAILURE = 'ADMIN_TXN_REPORT_FAILURE'

export const COMPANY_TXN_REPORT_SUCCESS = 'COMPANY_TXN_REPORT_SUCCESS';
export const COMPANY_TXN_REPORT_FAILURE = 'COMPANY_TXN_REPORT_FAILURE';

export const USER_TXN_REPORT_SUCCESS = 'USER_TXN_REPORT_SUCCESS';
export const USER_TXN_REPORT_FAILURE = 'USER_TXN_REPORT_FAILURE';

export const EMPLOYEE_TXN_REPORT_SUCCESS = 'EMPLOYEE_TXN_REPORT_SUCCESS';
export const EMPLOYEE_TXN_REPORT_FAILURE = 'EMPLOYEE_TXN_REPORT_FAILURE';

export const EMPLOYEE_PAN_REPORT_SUCCESS = 'EMPLOYEE_PAN_REPORT_SUCCESS';
export const EMPLOYEE_PAN_REPORT_FAILURE = 'EMPLOYEE_PAN_REPORT_FAILURE';
