export const RETAILER_ONBOARDING_REFERAL_CODE_SUCCESS = 'RETAILER_ONBOARDING_REFERAL_CODE_SUCCESS';
export const RETAILER_ONBOARDING_REFERAL_CODE_FAILURE = 'RETAILER_ONBOARDING_REFERAL_CODE_FAILURE';

export const RETAILER_ONBOARDING_SEND__OTP_SUCCESS = 'RETAILER_ONBOARDING_SEND__OTP_SUCCESS';
export const RETAILER_ONBOARDING_SEND__OTP_FAILURE = 'RETAILER_ONBOARDING_SEND__OTP_FAILURE';

export const RETAILER_OTP_SUBMIT_SUCCESS = 'RETAILER_OTP_SUBMIT_SUCCESS';
export const RETAILER_OTP_SUBMIT_FAILURE = 'RETAILER_OTP_SUBMIT_FAILURE';

export const RETAILER_SEND_EMAIL_OTP_SUCCESS = 'RETAILER_SEND_EMAIL_OTP_SUCCESS';
export const RETAILER_SEND_EMAIL_OTP_FAILURE = 'RETAILER_SEND_EMAIL_OTP_FAILURE';

export const RETAILER_RESEND_EMAIL_OTP_SUCCESS = 'RETAILER_RESEND_EMAIL_OTP_SUCCESS';
export const RETAILER_RESEND_EMAIL_OTP_FAILURE = 'RETAILER_RESEND_EMAIL_OTP_FAILURE';

export const RETAILER_SUBMIT_EMAIL_SUCCESS = 'RETAILER_SUBMIT_EMAIL_SUCCESS';
export const RETAILER_SUBMIT_EMAIL_FAILURE = 'RETAILER_SUBMIT_EMAIL_FAILURE';