export const RETAILER_ONBOARDING_REFERAL_CODE_SUCCESS = 'RETAILER_ONBOARDING_REFERAL_CODE_SUCCESS';
export const RETAILER_ONBOARDING_REFERAL_CODE_FAILURE = 'RETAILER_ONBOARDING_REFERAL_CODE_FAILURE';

export const RETAILER_ONBOARDING_SEND__OTP_SUCCESS = 'RETAILER_ONBOARDING_SEND__OTP_SUCCESS';
export const RETAILER_ONBOARDING_SEND__OTP_FAILURE = 'RETAILER_ONBOARDING_SEND__OTP_FAILURE';

export const RETAILER_OTP_SUBMIT_SUCCESS = 'RETAILER_OTP_SUBMIT_SUCCESS';
export const RETAILER_OTP_SUBMIT_FAILURE = 'RETAILER_OTP_SUBMIT_FAILURE';

export const RETAILER_SEND_EMAIL_OTP_SUCCESS = 'RETAILER_SEND_EMAIL_OTP_SUCCESS';
export const RETAILER_SEND_EMAIL_OTP_FAILURE = 'RETAILER_SEND_EMAIL_OTP_FAILURE';

export const RETAILER_RESEND_EMAIL_OTP_SUCCESS = 'RETAILER_RESEND_EMAIL_OTP_SUCCESS';
export const RETAILER_RESEND_EMAIL_OTP_FAILURE = 'RETAILER_RESEND_EMAIL_OTP_FAILURE';

export const RETAILER_SUBMIT_EMAIL_SUCCESS = 'RETAILER_SUBMIT_EMAIL_SUCCESS';
export const RETAILER_SUBMIT_EMAIL_FAILURE = 'RETAILER_SUBMIT_EMAIL_FAILURE';

export const RETAILER_POST_SHOP_DETAILS_SUCCESS = 'RETAILER_POST_SHOP_DETAILS_SUCCESS';
export const RETAILER_POST_SHOP_DETAILS_FAILURE = 'RETAILER_POST_SHOP_DETAILS_FAILURE';

// Aadhaar verification action types
export const RETAILER_AADHAAR_CONNECTION_SUCCESS = 'RETAILER_AADHAAR_CONNECTION_SUCCESS';
export const RETAILER_AADHAAR_CONNECTION_FAILURE = 'RETAILER_AADHAAR_CONNECTION_FAILURE';
export const RETAILER_DOWNLOAD_AADHAAR_SUCCESS = 'RETAILER_DOWNLOAD_AADHAAR_SUCCESS';
export const RETAILER_DOWNLOAD_AADHAAR_FAILURE = 'RETAILER_DOWNLOAD_AADHAAR_FAILURE';
export const RETAILER_UPLOAD_AADHAAR_SUCCESS = 'RETAILER_UPLOAD_AADHAAR_SUCCESS';
export const RETAILER_UPLOAD_AADHAAR_FAILURE = 'RETAILER_UPLOAD_AADHAAR_FAILURE';

// PAN verification action types
export const RETAILER_PAN_CONNECTION_SUCCESS = 'RETAILER_PAN_CONNECTION_SUCCESS';
export const RETAILER_PAN_CONNECTION_FAILURE = 'RETAILER_PAN_CONNECTION_FAILURE';
export const RETAILER_DOWNLOAD_PAN_SUCCESS = 'RETAILER_DOWNLOAD_PAN_SUCCESS';
export const RETAILER_DOWNLOAD_PAN_FAILURE = 'RETAILER_DOWNLOAD_PAN_FAILURE';
export const RETAILER_UPLOAD_PAN_SUCCESS = 'RETAILER_UPLOAD_PAN_SUCCESS';
export const RETAILER_UPLOAD_PAN_FAILURE = 'RETAILER_UPLOAD_PAN_FAILURE';

// Bank details action types
export const RETAILER_POST_BANK_DETAILS_SUCCESS = 'RETAILER_POST_BANK_DETAILS_SUCCESS';
export const RETAILER_POST_BANK_DETAILS_FAILURE = 'RETAILER_POST_BANK_DETAILS_FAILURE';

// Profile action types
export const RETAILER_POST_PROFILE_SUCCESS = 'RETAILER_POST_PROFILE_SUCCESS';
export const RETAILER_POST_PROFILE_FAILURE = 'RETAILER_POST_PROFILE_FAILURE';

// Get pending steps action types
export const RETAILER_GET_PENDING_SUCCESS = 'RETAILER_GET_PENDING_SUCCESS';
export const RETAILER_GET_PENDING_FAILURE = 'RETAILER_GET_PENDING_FAILURE';