export const ROLE_DEGRADE_COMPANY_USER_SUCCESS = 'ROLE_DEGRADE_COMPANY_USER_SUCCESS';
export const ROLE_DEGRADE_COMPANY_USER_FAILURE = 'ROLE_DEGRADE_COMPANY_USER_FAILURE';

export const ROLE_UPGRADE_COMPANY_USER_SUCCESS = 'ROLE_UPGRADE_COMPANY_USER_SUCCESS';
export const ROLE_UPGRADE_COMPANY_USER_FAILURE = 'ROLE_UPGRADE_COMPANY_USER_FAILURE';

export const ROLE_DEGRADE_MASTER_DISTRIBUTOR_SUCCESS = 'ROLE_DEGRADE_MASTER_DISTRIBUTOR_SUCCESS';
export const ROLE_DEGRADE_MASTER_DISTRIBUTOR_FAILURE = 'ROLE_DEGRADE_MASTER_DISTRIBUTOR_FAILURE';

export const ROLE_UPGRADE_MASTER_DISTRIBUTOR_SUCCESS= 'ROLE_UPGRADE_MASTER_DISTRIBUTOR_SUCCESS';
export const ROLE_UPGRADE_MASTER_DISTRIBUTOR_FAILURE = 'ROLE_UPGRADE_MASTER_DISTRIBUTOR_FAILURE';

export const ROLEDATA_COMPANY_USER_SUCCESS = 'ROLEDATA_COMPANY_USER_SUCCESS';
export const ROLEDATA_COMPANY_USER_FAILURE = 'ROLEDATA_COMPANY_USER_FAILURE';

export const ROLEDATA_MASTER_DISTRIBUTOR_SUCCESS = 'ROLEDATA_MASTER_DISTRIBUTOR_SUCCESS';
export const ROLEDATA_MASTER_DISTRIBUTOR_FAILURE = 'ROLEDATA_MASTER_DISTRIBUTOR_FAILURE';

// Used to clear role success/error messages after showing notifications
export const ROLE_CLEAR_STATUS = 'ROLE_CLEAR_STATUS';