export const ROLE_DEGRADE_COMPANY_USER_SUCCESS = 'ROLE_DEGRADE_COMPANY_USER_SUCCESS';
export const ROLE_DEGRADE_COMPANY_USER_FAILURE = 'ROLE_DEGRADE_COMPANY_USER_FAILURE';

export const ROLE_UPGRADE_COMPANY_USER_SUCCESS = 'ROLE_UPGRADE_COMPANY_USER_SUCCESS';
export const ROLE_UPGRADE_COMPANY_USER_FAILURE = 'ROLE_UPGRADE_COMPANY_USER_FAILURE';

export const ROLE_DEGRADE_MASTER_DISTRIBUTOR_SUCCESS = 'ROLE_DEGRADE_MASTER_DISTRIBUTOR_SUCCESS';
export const ROLE_DEGRADE_MASTER_DISTRIBUTOR_FAILURE = 'ROLE_DEGRADE_MASTER_DISTRIBUTOR_FAILURE';

export const ROLE_UPGRADE_MASTER_DISTRIBUTOR_SUCCESS= 'ROLE_UPGRADE_MASTER_DISTRIBUTOR_SUCCESS';
export const ROLE_UPGRADE_MASTER_DISTRIBUTOR_FAILURE = 'ROLE_UPGRADE_MASTER_DISTRIBUTOR_SUCCESS';
