export const SERVICE_LIST_SUCCESS = "SERVICE_LIST_SUCCESS";
export const SERVICE_LIST_FAILURE = "SERVICE_LIST_FAILURE";

export const SERVICE_CREATE_SUCCESS = "SERVICE_CREATE_SUCCESS";
export const SERVICE_CREATE_FAILURE = "SERVICE_CREATE_FAILURE";

export const SERVICE_UPDATE_SUCCESS = "SERVICE_UPDATE_SUCCESS";
export const SERVICE_UPDATE_FAILURE = "SERVICE_UPDATE_FAILURE";

export const EMPLOYEE_SERVICE_LIST_SUCCESS = "EMPLOYEE_SERVICE_LIST_SUCCESS";
export const EMPLOYEE_SERVICE_LIST_FAILURE = "EMPLOYEE_SERVICE_LIST_FAILURE";

export const EMPLOYEE_SERVICE_CREATE_SUCCESS = "EMPLOYEE_SERVICE_CREATE_SUCCESS";
export const EMPLOYEE_SERVICE_CREATE_FAILURE = "EMPLOYEE_SERVICE_CREATE_FAILURE";

export const EMPLOYEE_SERVICE_UPDATE_SUCCESS = "EMPLOYEE_SERVICE_UPDATE_SUCCESS";
export const EMPLOYEE_SERVICE_UPDATE_FAILURE = "EMPLOYEE_SERVICE_UPDATE_FAILURE";

