export const SLAB_CREATE_START = 'SLAB_CREATE_START';
export const SLAB_CREATE_SUCCESS = 'SLAB_CREATE_SUCCESS';
export const SLAB_CREATE_FAILURE = 'SLAB_CREATE_FAILURE';

export const SLAB_UPDATE_START = 'SLAB_UPDATE_START';
export const SLAB_UPDATE_SUCCESS = 'SLAB_UPDATE_SUCCESS';
export const SLAB_UPDATE_FAILURE = 'SLAB_UPDATE_FAILURE';

export const SLAB_GET_LIST_START = 'SLAB_GET_LIST_START';
export const SLAB_GET_LIST_SUCCESS = 'SLAB_GET_LIST_SUCCESS';
export const SLAB_GET_LIST_FAILURE = 'SLAB_GET_LIST_FAILURE';

export const SLAB_GET_COMM_SUCCESS = 'SLAB_GET_COMM_SUCCESS';
export const SLAB_GET_COMM_FAILURE = 'SLAB_GET_COMM_FAILURE';


export const SLAB_UPDATE_COMM_START = 'SLAB_UPDATE_COMM_START';
export const SLAB_UPDATE_COMM_SUCCESS = 'SLAB_UPDATE_COMM_SUCCESS';
export const SLAB_UPDATE_COMM_FAILURE = 'SLAB_UPDATE_COMM_FAILURE';

export const SLAB_ASSIGN_START = 'SLAB_ASSIGN_START';
export const SLAB_ASSIGN_SUCCESS = 'SLAB_ASSIGN_SUCCESS';
export const SLAB_ASSIGN_FAILURE = 'SLAB_ASSIGN_FAILURE';

export const SLAB_GET_VISIBILITY_START = 'SLAB_GET_VISIBILITY_START';
export const SLAB_GET_VISIBILITY_SUCCESS = 'SLAB_GET_VISIBILITY_SUCCESS';
export const SLAB_GET_VISIBILITY_FAILURE = 'SLAB_GET_VISIBILITY_FAILURE';
