export const SUBSCRIPTION_GET_LIST_START = 'SUBSCRIPTION_GET_LIST_START';
export const SUBSCRIPTION_GET_LIST_SUCCESS = 'SUBSCRIPTION_GET_LIST_SUCCESS';
export const SUBSCRIPTION_GET_LIST_FAILURE = 'SUBSCRIPTION_GET_LIST_FAILURE';
