export const SUBSCRIPTION_GET_LIST_START = 'SUBSCRIPTION_GET_LIST_START';
export const SUBSCRIPTION_GET_LIST_SUCCESS = 'SUBSCRIPTION_GET_LIST_SUCCESS';
export const SUBSCRIPTION_GET_LIST_FAILURE = 'SUBSCRIPTION_GET_LIST_FAILURE';
export const SUBSCRIPTION_UPGRADE_START = 'SUBSCRIPTION_UPGRADE_START';
export const SUBSCRIPTION_UPGRADE_SUCCESS = 'SUBSCRIPTION_UPGRADE_SUCCESS';
export const SUBSCRIPTION_UPGRADE_FAILURE = 'SUBSCRIPTION_UPGRADE_FAILURE';

export const SUBSCRIPTION_USER_UPGRADE_SUCCESS = 'SUBSCRIPTION_USER_UPGRADE_SUCCESS';
export const SUBSCRIPTION_USER_UPGRADE_FAILURE = 'SUBSCRIPTION_USER_UPGRADE_FAILURE';
