export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_UNAUTHORIZED = 'GET_PROFILE_UNAUTHORIZED';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const ADMIN_ROLES_PERMISSION_SUCCESS = 'ADMIN_ROLES_PERMISSION_SUCCESS';
export const ADMIN_ROLES_PERMISSION_FAILURE = 'ADMIN_ROLES_PERMISSION_FAILURE';

export const UPDATE_ROLES_PERMISSION_SUCESS = 'UPDATE_ROLES_PERMISSION_SUCESS';
export const UPDATE_ROLES_PERMISSION_FAILURE = 'UPDATE_ROLES_PERMISSION_FAILURE';

export const ADD_BANK_DETAILS_SUCCESS = 'ADD_BANK_DETAILS_SUCCESS';
export const ADD_BANK_DETAILS_FAILURE = 'ADD_BANK_DETAILS_FAILURE';

export const ADD_BANK_COMPANY_SUCCESS = 'ADD_BANK_COMPANY_SUCCESS';
export const ADD_BANK_COMPANY_FAILURE = 'ADD_BANK_COMPANY_FAILURE';

export const ADD_BANK_ADMIN_SUCCESS = 'ADD_BANK_ADMIN_SUCCESS';
export const ADD_BANK_ADMIN_FAILURE = 'ADD_BANK_ADMIN_FAILURE';

