export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_UNAUTHORIZED = 'GET_PROFILE_UNAUTHORIZED';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

