export const WALLET_ALS_SUCCESS = 'WALLET_ALS_SUCCESS';
export const WALLET_ALS_FAILURE = 'WALLET_ALS_FAILURE';
export const WALLET_BALANCE_SUCCESS = 'WALLET_BALANCE_SUCCESS';
export const WALLET_BALANCE_FAILURE = 'WALLET_BALANCE_FAILURE';
export const COMPANY_WALLET_BALANCE_SUCCESS = 'COMPANY_WALLET_BALANCE_SUCCESS';
export const COMPANY_WALLET_BALANCE_FAILURE = 'COMPANY_WALLET_BALANCE_FAILURE';
export const USER_WALLET_BALANCE_SUCCESS = 'USER_WALLET_BALANCE_SUCCESS';
export const USER_WALLET_BALANCE_FAILURE = 'USER_WALLET_BALANCE_FAILURE';
export const EKYC_HUB_BALANCE_SUCCESS = 'EKYC_HUB_BALANCE_SUCCESS';
export const EKYC_HUB_BALANCE_FAILURE = 'EKYC_HUB_BALANCE_FAILURE';
export const INSPAY_WALLET_BALANCE_SUCCESS = 'INSPAY_WALLET_BALANCE_SUCCESS';
export const INSPAY_WALLET_BALANCE_FAILURE = 'INSPAY_WALLET_BALANCE_FAILURE';
export const BBPS_WALLET_BALANCE_SUCCESS = 'BBPS_WALLET_BALANCE_SUCCESS';
export const BBPS_WALLET_BALANCE_FAILURE = 'BBPS_WALLET_BALANCE_FAILURE';
export const DASHBOARD_STATISTICS_SUCCESS = 'DASHBOARD_STATISTICS_SUCCESS';
export const DASHBOARD_STATISTICS_FAILURE = 'DASHBOARD_STATISTICS_FAILURE';
export const USER_DASHBOARD_STATISTICS_SUCCESS = 'USER_DASHBOARD_STATISTICS_SUCCESS';
export const USER_DASHBOARD_STATISTICS_FAILURE = 'USER_DASHBOARD_STATISTICS_FAILURE';

export const UPLOAD_FEVICON_SUCCESS = 'UPLOAD_FEVICON_SUCCESS';
export const UPLOAD_FEVICON_FAILURE = 'UPLOAD_FEVICON_FAILURE';

export const WALLET_HISTORY_COMPANY_SUCCESS = "WALLET_HISTORY_COMPANY_SUCCESS";
export const WALLET_HISTORY_COMPANY_FAILURE = "WALLET_HISTORY_COMPANY_FAILURE";