export const WALLET_ALS_SUCCESS = 'WALLET_ALS_SUCCESS';
export const WALLET_ALS_FAILURE = 'WALLET_ALS_FAILURE';
export const WALLET_BALANCE_SUCCESS = 'WALLET_BALANCE_SUCCESS';
export const WALLET_BALANCE_FAILURE = 'WALLET_BALANCE_FAILURE';
