export const WHITELABEL_CREATE_SUCCESS = 'WHITELABEL_CREATE_SUCCESS';
export const WHITELABEL_CREATE_FAILURE = 'WHITELABEL_CREATE_FAILURE';

export const GET_PINCODE_BY_CITY_SUCCESS = 'GET_PINCODE_BY_CITY_SUCCESS';
export const GET_PINCODE_BY_CITY_FAILURE = 'GET_PINCODE_BY_CITY_FAILURE';

export const GET_CITY_BY_PINCODE_SUCCESS = 'GET_CITY_BY_PINCODE_SUCCESS';
export const GET_CITY_BY_PINCODE_FAILURE = 'GET_CITY_BY_PINCODE_FAILURE';

export const GET_IP_CHECK_SUCCESS = 'GET_IP_CHECK_SUCCESS';
export const GET_IP_CHECK_FAILURE = 'GET_IP_CHECK_FAILURE';

export const GET_PANDATA_FETCH_SUCCESS = 'GET_PANDATA_FETCH_SUCCESS';
export const GET_PANDATA_FETCH_FAILURE = 'GET_PANDATA_FETCH_FAILURE';
