export const WHITELABEL_CREATE_SUCCESS = 'WHITELABEL_CREATE_SUCCESS';
export const WHITELABEL_CREATE_FAILURE = 'WHITELABEL_CREATE_FAILURE';

export const GET_PINCODE_BY_CITY_SUCCESS = 'GET_PINCODE_BY_CITY_SUCCESS';
export const GET_PINCODE_BY_CITY_FAILURE = 'GET_PINCODE_BY_CITY_FAILURE';

export const GET_CITY_BY_PINCODE_SUCCESS = 'GET_CITY_BY_PINCODE_SUCCESS';
export const GET_CITY_BY_PINCODE_FAILURE = 'GET_CITY_BY_PINCODE_FAILURE';

export const GET_IP_CHECK_SUCCESS = 'GET_IP_CHECK_SUCCESS';
export const GET_IP_CHECK_FAILURE = 'GET_IP_CHECK_FAILURE';

export const GET_PANDATA_FETCH_SUCCESS = 'GET_PANDATA_FETCH_SUCCESS';
export const GET_PANDATA_FETCH_FAILURE = 'GET_PANDATA_FETCH_FAILURE';

export const GET_WHITELABEL_LIST_SUCCESS = 'GET_WHITELABEL_LIST_SUCCESS';
export const GET_WHITELABEL_LIST_FAILURE = 'GET_WHITELABEL_LIST_FAILURE';

export const FETCH_KYC_DETAILS_SUCCESS = 'FETCH_KYC_DETAILS_SUCCESS';
export const FETCH_KYC_DETAILS_FAILURE = 'FETCH_KYC_DETAILS_FAILURE';

export const GET_KYCSTATUS_SUCCESS = 'GET_KYCSTATUS_SUCCESS';
export const GET_KYCSTATUS_FAILURE = 'GET_KYCSTATUS_FAILURE';

export const UPDATE_KYCSTATUS_SUCCESS = 'UPDATE_KYCSTATUS_SUCCESS';
export const UPDATE_KYCSTATUS_FAILURE = 'UPDATE_KYCSTATUS_FAILURE';

export const KYC_LOCK_STATUS_SUCCESS = 'KYC_LOCK_STATUS_SUCCESS';
export const KYC_LOCK_STATUS_FAILURE = 'KYC_LOCK_STATUS_FAILURE';

export const REVERT_KYC_DETAILS_SUCCESS = 'REVERT_KYC_DETAILS_SUCCESS';
export const REVERT_KYC_DETAILS_FAILURE = 'REVERT_KYC_DETAILS_FAILURE';

export const RESEND_ONBOARDING_LINK_SUCCESS = 'RESEND_ONBOARDING_LINK_SUCCESS';
export const RESEND_ONBOARDING_LINK_FAILURE = 'RESEND_ONBOARDING_LINK_FAILURE';

export const DEACTIVATE_ONBOARDING_LINK_SUCCESS = 'DEACTIVATE_ONBOARDING_LINK_SUCCESS';
export const DEACTIVATE_ONBOARDING_LINK_FAILURE = 'DEACTIVATE_ONBOARDING_LINK_FAILURE';
