export { default as Auth } from './Auth';
export const Dashboard = () => <div>Dashboard</div>;
export const AdminDashboard = () => <div>AdminDashboard</div>;
export const SubAdminDashboard = () => <div>SubAdminDashboard</div>;
export const RetailerDashboard = () => <div>RetailerDashboard</div>;
export const MasterDistributerDashboard = () => <div>MasterDistributerDashboard</div>;
export const DistributerDashboard = () => <div>DistributerDashboard</div>;
export const ApiUserDashboard = () => <div>ApiUserDashboard</div>;
export const SalesManagerDashboard = () => <div>SalesManagerDashboard</div>;
export const SalesExecutiveDashboard = () => <div>SalesExecutiveDashboard</div>;
export const CustomerCareDashboard = () => <div>CustomerCareDashboard</div>;
export const EmployeeDashboard = () => <div>EmployeeDashboard</div>;
